//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDD_ConsultorioDermatologicoEntities : DbContext
    {
        public BDD_ConsultorioDermatologicoEntities()
            : base("name=BDD_ConsultorioDermatologicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAntecedenteGinecoObstetrico> tblAntecedenteGinecoObstetrico { get; set; }
        public virtual DbSet<tblAntecedenteReprodMasculino> tblAntecedenteReprodMasculino { get; set; }
        public virtual DbSet<tblCIE10> tblCIE10 { get; set; }
        public virtual DbSet<tblContactoEmergencia> tblContactoEmergencia { get; set; }
        public virtual DbSet<tblEstadoCivil> tblEstadoCivil { get; set; }
        public virtual DbSet<tblEvolucion> tblEvolucion { get; set; }
        public virtual DbSet<tblFotos> tblFotos { get; set; }
        public virtual DbSet<tblHistoriaClinica> tblHistoriaClinica { get; set; }
        public virtual DbSet<tblIdentidadGenero> tblIdentidadGenero { get; set; }
        public virtual DbSet<tblLateralidad> tblLateralidad { get; set; }
        public virtual DbSet<tblNivelEducacion> tblNivelEducacion { get; set; }
        public virtual DbSet<tblOrientacionSexual> tblOrientacionSexual { get; set; }
        public virtual DbSet<tblPaciente> tblPaciente { get; set; }
        public virtual DbSet<tblReligion> tblReligion { get; set; }
        public virtual DbSet<tblSeguroMedico> tblSeguroMedico { get; set; }
        public virtual DbSet<tblTipoDiscapacidad> tblTipoDiscapacidad { get; set; }
        public virtual DbSet<tblTipoSangre> tblTipoSangre { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    }
}
