//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAntecedenteGinecoObstetrico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAntecedenteGinecoObstetrico()
        {
            this.tblHistoriaClinica = new HashSet<tblHistoriaClinica>();
        }
    
        public int idAntecedenteGinecoObstetrico { get; set; }
        public string menarquia { get; set; }
        public string ciclo { get; set; }
        public Nullable<System.DateTime> fechaUltimaMenstruacion { get; set; }
        public Nullable<System.DateTime> gestas { get; set; }
        public string partos { get; set; }
        public string cesarea { get; set; }
        public string abortos { get; set; }
        public Nullable<int> hijosVivos { get; set; }
        public Nullable<int> hijosMuertos { get; set; }
        public string vidaSexualActiva { get; set; }
        public string metodoPlanificacionFamiliar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistoriaClinica> tblHistoriaClinica { get; set; }
    }
}
