//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFotoMapaCorporal
    {
        public int idFotoMapaCorporal { get; set; }
        public byte[] fotoMapaCorporal { get; set; }
        public string nombreFotoMapaCorporal { get; set; }
    }
}
