//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoriaClinica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHistoriaClinica()
        {
            this.tblEvolucion = new HashSet<tblEvolucion>();
        }
    
        public int idHistoriaClinica { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idSeguroMedico { get; set; }
        public string tipoSangre { get; set; }
        public string antecedenteFamiliarClinico { get; set; }
        public string antecedenteFamiliarQuirurgico { get; set; }
        public string antecedentePersonalClinico { get; set; }
        public string antecedentePersonalQuirurgico { get; set; }
        public string antecedentePersonalAlergico { get; set; }
        public string antecedentePersonalVacunas { get; set; }
        public Nullable<int> idAntecedenteGinecoObstetrico { get; set; }
        public Nullable<int> idAntecedenteReprodMasculino { get; set; }
        public string tabaco { get; set; }
        public string alcohol { get; set; }
        public string otrasDrogas { get; set; }
        public string actividadFisica { get; set; }
        public string medicacionHabitual { get; set; }
        public Nullable<int> habilitado { get; set; }
    
        public virtual tblAntecedenteGinecoObstetrico tblAntecedenteGinecoObstetrico { get; set; }
        public virtual tblAntecedenteReprodMasculino tblAntecedenteReprodMasculino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvolucion> tblEvolucion { get; set; }
        public virtual tblPaciente tblPaciente { get; set; }
        public virtual tblSeguroMedico tblSeguroMedico { get; set; }
    }
}
