//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPaciente()
        {
            this.tblHistoriaClinica = new HashSet<tblHistoriaClinica>();
        }
    
        public int idPaciente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> idIdentidadGenero { get; set; }
        public Nullable<int> idOrientacionSexual { get; set; }
        public string ciudadNacimiento { get; set; }
        public string ciudadResidencia { get; set; }
        public string ocupacion { get; set; }
        public string profesion { get; set; }
        public Nullable<int> idTipoDiscapacidad { get; set; }
        public Nullable<int> porcentajeDiscapacidad { get; set; }
        public Nullable<int> idEstadoCivil { get; set; }
        public Nullable<int> idLateralidad { get; set; }
        public Nullable<int> idNivelEducacion { get; set; }
        public string direccion { get; set; }
        public string telefonoPersonal { get; set; }
        public string telefonoResidencial { get; set; }
        public string correoElectronico { get; set; }
        public Nullable<int> idReligion { get; set; }
        public Nullable<int> idContactoEmergencia { get; set; }
        public Nullable<int> habilitado { get; set; }
    
        public virtual tblContactoEmergencia tblContactoEmergencia { get; set; }
        public virtual tblEstadoCivil tblEstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistoriaClinica> tblHistoriaClinica { get; set; }
        public virtual tblIdentidadGenero tblIdentidadGenero { get; set; }
        public virtual tblLateralidad tblLateralidad { get; set; }
        public virtual tblNivelEducacion tblNivelEducacion { get; set; }
        public virtual tblOrientacionSexual tblOrientacionSexual { get; set; }
        public virtual tblReligion tblReligion { get; set; }
        public virtual tblTipoDiscapacidad tblTipoDiscapacidad { get; set; }
    }
}
