//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeguroMedico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeguroMedico()
        {
            this.tblHistoriaClinica = new HashSet<tblHistoriaClinica>();
        }
    
        public int idSeguroMedico { get; set; }
        public string nombreSeguro { get; set; }
        public Nullable<int> habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistoriaClinica> tblHistoriaClinica { get; set; }
    }
}
