//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioDermatologico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public int idUsuario { get; set; }
        public string nombresUsuario { get; set; }
        public string apellidosUsuario { get; set; }
        public string cedulaUsuario { get; set; }
        public string rolUsuario { get; set; }
        public string aliasUsuario { get; set; }
        public string contraseñaUsuario { get; set; }
        public string correoUsuario { get; set; }
        public string codigoMSP { get; set; }
    }
}
